### ISSUE TITLE
Strange Numbers after Variable changing

### ISSUE THREAD

**Issue by Njma** [er77/EssBase.ACT#10]
Hello, Evgeniy!
Thank you a lot for this tool!
While using your ribbon I've found strange numbers in Scripts Calc Window after Sub.Variable changing.
Is it ok or something going wrong?
![capture](https://user-images.githubusercontent.com/32389156/31013658-c21dc656-a51f-11e7-8943-b234c04969b0.JPG)
Thanks!

**Comment by er77** [comment]
It was fixed in 2.%x version. Please updated
